In [1]:
import numpy as np
import re

In [2]:
input_file = "test_input.txt"

In [16]:
with open(input_file) as fh:
    input = fh.readlines()

In [17]:
input

['0,9 -> 5,9\n',
 '8,0 -> 0,8\n',
 '9,4 -> 3,4\n',
 '2,2 -> 2,1\n',
 '7,0 -> 7,4\n',
 '6,4 -> 2,0\n',
 '0,9 -> 2,9\n',
 '3,4 -> 1,4\n',
 '0,0 -> 8,8\n',
 '5,5 -> 8,2']

In [18]:
input = [[[int(n) for n in c.split(',')] for c in i.split(' -> ')] for i in input]
input

[[[0, 9], [5, 9]],
 [[8, 0], [0, 8]],
 [[9, 4], [3, 4]],
 [[2, 2], [2, 1]],
 [[7, 0], [7, 4]],
 [[6, 4], [2, 0]],
 [[0, 9], [2, 9]],
 [[3, 4], [1, 4]],
 [[0, 0], [8, 8]],
 [[5, 5], [8, 2]]]

In [23]:
inp = np.array(input)

In [24]:
inp.shape

(10, 2, 2)

In [26]:
xs = inp[:, :, 0]
ys = inp[:, :, 1]

In [27]:
max_x = xs.max()
max_y = ys.max()

In [60]:
grid = np.zeros((max_x+1, max_y+1), dtype=int)
grid

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [61]:
for i in input:
    st, fi = i
    x0, y0 = st
    x1, y1 = fi
    print(x0, y0, x1, y1, x0 == x1, y0 == y1, (x0 == x1 or y0 == y1))
    if (x0 == x1 or y0 == y1):
        xs = min(x0, x1)
        xf = max(x0, x1)
        ys = min(y0, y1)
        yf = max(y0, y1)
        grid[ys:yf+1, xs:xf+1] += 1

0 9 5 9 False True True
8 0 0 8 False False False
9 4 3 4 False True True
2 2 2 1 True False True
7 0 7 4 True False True
6 4 2 0 False False False
0 9 2 9 False True True
3 4 1 4 False True True
0 0 8 8 False False False
5 5 8 2 False False False


In [62]:
grid

array([[0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 1, 1, 2, 1, 1, 1, 2, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [2, 2, 2, 1, 1, 1, 0, 0, 0, 0]])

5

In [7]:
draws = [int(i) for i in input[0].split(',')]

In [118]:
def get_board(lines: list):
    board = []
    for j in lines:
        line = []
        for i in re.split('\s+', j):
            try:
                line.append(int(i))
            except:
                pass
        board.append(line)
    board = np.array(board)
    assert board.shape == (5, 5)
    
    return board

In [31]:
boards = []
for i in range(2, len(input), 6):
    boards.append(get_board(input[i:i+5]))

In [33]:
boards = np.array(boards)

In [117]:
list(range(2, len(input), 6))

[2, 8, 14]

In [119]:
def parse_input(inp: list):
    draws = [int(i) for i in input[0].split(',')]
    
    boards = []
    for i in range(2, len(input), 6):
        boards.append(get_board(input[i:i+5]))
        
    boards = np.array(boards)
    
    return draws, boards

In [120]:
draws, boards = parse_input(input)

In [121]:
boards.shape

(3, 5, 5)

In [122]:
boards

array([[[22, 13, 17, 11,  0],
        [ 8,  2, 23,  4, 24],
        [21,  9, 14, 16,  7],
        [ 6, 10,  3, 18,  5],
        [ 1, 12, 20, 15, 19]],

       [[ 3, 15,  0,  2, 22],
        [ 9, 18, 13, 17,  5],
        [19,  8,  7, 25, 23],
        [20, 11, 10, 24,  4],
        [14, 21, 16, 12,  6]],

       [[14, 21, 17, 24,  4],
        [10, 16, 15,  9, 19],
        [18,  8, 23, 26, 20],
        [22, 11, 13,  6,  5],
        [ 2,  0, 12,  3,  7]]])

In [129]:
for draw in draws[11:12]:
    mask = boards == draw
    boards[mask] = -1
print(boards)

[[[22 13 -1 -1 -1]
  [ 8 -1 -1 -1 -1]
  [-1 -1 -1 16 -1]
  [ 6 10  3 18 -1]
  [ 1 12 20 15 19]]

 [[ 3 15 -1 -1 22]
  [-1 18 13 -1 -1]
  [19  8 -1 25 -1]
  [20 -1 10 -1 -1]
  [-1 -1 16 12  6]]

 [[-1 -1 -1 -1 -1]
  [10 16 15 -1 19]
  [18  8 -1 26 20]
  [22 -1 13  6 -1]
  [-1 -1 12  3 -1]]]


In [130]:
mark = boards == -1
mark

array([[[False, False,  True,  True,  True],
        [False,  True,  True,  True,  True],
        [ True,  True,  True, False,  True],
        [False, False, False, False,  True],
        [False, False, False, False, False]],

       [[False, False,  True,  True, False],
        [ True, False, False,  True,  True],
        [False, False,  True, False,  True],
        [False,  True, False,  True,  True],
        [ True,  True, False, False, False]],

       [[ True,  True,  True,  True,  True],
        [False, False, False,  True, False],
        [False, False,  True, False, False],
        [False,  True, False, False,  True],
        [ True,  True, False, False,  True]]])

In [131]:
col_win = mark.all(axis=1)
col_win

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [132]:
row_win = mark.all(axis=2)
row_win

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [ True, False, False, False, False]])

In [133]:
board_win = row_win.any(axis=1) | col_win.any(axis=1)
board_win

array([False, False,  True])

In [137]:
if board_win.any():
    winning_board = boards[board_win,...]
    score = (winning_board * (1-mark[board_win,...])).sum()
    print(score)
    print(draws)
    print(score * draw)

188
[7, 4, 9, 5, 11, 17, 23, 2, 0, 14, 21, 24, 10, 16, 13, 6, 15, 25, 12, 22, 18, 20, 8, 19, 3, 26, 1]
4512


In [135]:
winning_board

array([[[-1, -1, -1, -1, -1],
        [10, 16, 15, -1, 19],
        [18,  8, -1, 26, 20],
        [22, -1, 13,  6, -1],
        [-1, -1, 12,  3, -1]]])

In [136]:
mark

array([[[False, False,  True,  True,  True],
        [False,  True,  True,  True,  True],
        [ True,  True,  True, False,  True],
        [False, False, False, False,  True],
        [False, False, False, False, False]],

       [[False, False,  True,  True, False],
        [ True, False, False,  True,  True],
        [False, False,  True, False,  True],
        [False,  True, False,  True,  True],
        [ True,  True, False, False, False]],

       [[ True,  True,  True,  True,  True],
        [False, False, False,  True, False],
        [False, False,  True, False, False],
        [False,  True, False, False,  True],
        [ True,  True, False, False,  True]]])

In [138]:
prev_board_win = np.full(boards.shape[0], False)

In [140]:
~prev_board_win

array([ True,  True,  True])