In [1]:
import numpy as np
import re

In [2]:
input_file = "test_input.txt"

In [3]:
with open(input_file) as fh:
    input = fh.readlines()

In [5]:
input = [int(i) for i in input[0].split(',')]
input

[3, 4, 3, 1, 2]

In [7]:
num_states = 9
state = np.bincount(input, minlength=9)

In [8]:
state

array([0, 1, 1, 2, 1, 0, 0, 0, 0])

In [11]:
num_days = 3
for _ in range(num_days):
    new_state = np.zeros_like(state)
    new_state[:num_states-1] = state[1:num_states]
    new_state[6] += state[0]
    new_state[8] += state[0]
    print(new_state)
    print(state)
    state = new_state

[1 1 2 1 0 0 0 0 0]
[0 1 1 2 1 0 0 0 0]
[1 2 1 0 0 0 1 0 1]
[1 1 2 1 0 0 0 0 0]
[2 1 0 0 0 1 1 1 1]
[1 2 1 0 0 0 1 0 1]
